services:
  nexus:
    image: ghcr.io/zuperhunt/nexus-prover:latest
    environment:
      - NONINTERACTIVE=1
      - RUST_BACKTRACE=full
    volumes:
      - ./storage:/root/.nexus:z
    deploy:
      resources:
        # Atur limit CPU dan Memory di sini
        # Tipe data harus string
        limits:
          cpus: '2'
          memory: '2G'
