name: Push to container registry

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tags
        if: ${{ github.event_name == 'release' }}
        run: echo "name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Generate Docker image metadata
        uses: docker/metadata-action@v5.4.0
        id: img_meta
        with:
          flavor: |
            latest=auto
          images: ghcr.io/${{ github.repository }}
          tags: |
            ${{ steps.tags.outputs.name }}
            latest

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./
          tags: ${{ steps.img_meta.outputs.tags }}
          labels: ${{ steps.img_meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
